services:
  postgres:
    image: postgres:16
    container_name: spring-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: realestate
      POSTGRES_USER: ${REALESTATE_DB_USER}
      POSTGRES_PASSWORD: ${REALESTATE_DB_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: generic-workflow-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/realestate
      SPRING_DATASOURCE_USERNAME: ${REALESTATE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${REALESTATE_DB_PASS}
      REALESTATE_BASE_DIRECTORY: ${REALESTATE_BASE_DIRECTORY}
      REALESTATE_JWT_SECRET: ${REALESTATE_JWT_SECRET}
      JAVA_OPTS: ${JAVA_OPTS}

    volumes:
      - realestate_data:/data/realestate

    restart: unless-stopped

volumes:
  pg_data:
  realestate_data:
